# Generated by Django 2.1.3 on 2018-11-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
